#!/bin/sh
exec java -jar jassh.jar -nocompdaemon -usejavacp -savecompiled "$0" "$@"
!#
val host=if (args.size>0) args(0) else "localhost"
val user=if (args.size>1) args(1) else util.Properties.userName
val freq=if (args.size>2) args(2) else ""
val numb=if (args.size>3) args(3) else ""
val vmstatcmd="vmstat %s %s".format(freq, numb)

jassh.SSH.once(host, user)  {
  //_.run(vmstatcmd, {l=> println(l getOrElse "")}).waitForEnd
  _.run(vmstatcmd, _.foreach(println _)).waitForEnd
}
