#!/bin/sh
# -Yrepl-sync
exec java -jar ../target/jassh.jar -nocompdaemon -usejavacp -savecompiled "$0" "$@"
!#

import scala.actors._
import Actor._

import fr.janalyse.ssh._
SSH.connect(host = "localhost", username = "test") { ssh =>
  val caller = self
  val receiver = actor {
    loop {
      react {
        case e: StandardOutputMessage => println(e.line)
        case _: StandardOutputClosed => caller ! "That's all folks"; exit
        case _ =>
      }
    }
  }
  val executor = ssh.run("vmstat 1 10", receiver)
  receive {case _ => }
  executor.close
}

